# Generated by Django 5.0.3 on 2024-03-31 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_cateory_contact_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cateory',
            new_name='Category',
        ),
    ]
