# Generated by Django 5.0.3 on 2024-03-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
